# Generated by build/generate-r8-rules.sh - do not edit by hand; edit the script and re-run.
#
# Keep-rules for consuming Android applications that build with R8 (AndroidLinkTool=r8).
# See the .targets alongside for why .NET for Android needs these shipped explicitly.

# ---- upstream consumer rules (sfmcsdk-3.1.1.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- upstream consumer rules (common-internal-1.0.0.aar proguard.txt), shipped verbatim ----
# Consumer ProGuard rules
# These rules are applied to consumer applications to prevent ProGuard crashes

# Keep Everything in the SDK Package
-keep class com.salesforce.marketingcloud.** { *; }
-keep @interface com.salesforce.marketingcloud.**
-keep enum com.salesforce.marketingcloud.** { *; }
# Android Parcelable patterns.
-keepclassmembers class com.salesforce.marketingcloud.** implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
-keepnames class com.salesforce.marketingcloud.** implements android.os.Parcelable

# Firebase messaging protection for consumers
-keep class com.google.firebase.messaging.** { *; }
-dontwarn com.google.firebase.messaging.**

# Prevent obfuscation warnings
-dontwarn com.salesforce.marketingcloud.**
# ---- curated: the JNI-only entry surface C# reaches (invisible to R8) ----

# The SDK entry point and its configuration builder are constructed and called only from C#.
-keep class com.salesforce.marketingcloud.sfmcsdk.SFMCSdk { *; }
-keep class com.salesforce.marketingcloud.sfmcsdk.SFMCSdk$Companion { *; }
-keep class com.salesforce.marketingcloud.sfmcsdk.SFMCSdkModuleConfig { *; }
-keep class com.salesforce.marketingcloud.sfmcsdk.SFMCSdkModuleConfig$Builder { *; }
-keep class com.salesforce.marketingcloud.sfmcsdk.InitializationStatus { *; }

# Identity and event tracking are driven from C# on instances handed out by the SDK; keeping the
# interfaces keeps their implementations on live classes.
-keep class com.salesforce.marketingcloud.sfmcsdk.components.identity.Identity { *; }
-keep class com.salesforce.marketingcloud.sfmcsdk.components.events.** { *; }

# The Kotlin function types the callback bridge implements from C#.
-keep class kotlin.jvm.functions.Function1 { *; }
-keep class kotlin.Unit { *; }
